// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace CompanyEmployees.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CompanyId");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("60f3fb1e-20c7-443a-9e3f-c9d4606a1af2"),
                            Address = "Bangalore",
                            Country = "India",
                            Name = "IT Solution Limited"
                        },
                        new
                        {
                            Id = new Guid("559fbd83-c758-4d5d-b62a-43f7ee6c66ed"),
                            Address = "Kolkata",
                            Country = "India",
                            Name = "Admin Solution Limited"
                        });
                });

            modelBuilder.Entity("Entities.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EmployeeId");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9208e2f4-0040-450f-ab9f-672e570d31bf"),
                            Age = 35,
                            CompanyId = new Guid("60f3fb1e-20c7-443a-9e3f-c9d4606a1af2"),
                            Name = "Deepika Padukone",
                            Position = "Director"
                        },
                        new
                        {
                            Id = new Guid("61cf9b60-b44f-4fdb-a3e8-92aedee59bd5"),
                            Age = 32,
                            CompanyId = new Guid("559fbd83-c758-4d5d-b62a-43f7ee6c66ed"),
                            Name = "Kriti Sanon",
                            Position = "CEO"
                        },
                        new
                        {
                            Id = new Guid("e38b7b92-317e-4388-8188-0640e46cabfa"),
                            Age = 37,
                            CompanyId = new Guid("60f3fb1e-20c7-443a-9e3f-c9d4606a1af2"),
                            Name = "Aditya Kapoor",
                            Position = "Executive"
                        },
                        new
                        {
                            Id = new Guid("61d4de3d-b743-471d-844a-501c02e88bad"),
                            Age = 42,
                            CompanyId = new Guid("559fbd83-c758-4d5d-b62a-43f7ee6c66ed"),
                            Name = "Rani Mukherjee",
                            Position = "Founder"
                        });
                });

            modelBuilder.Entity("Entities.Models.Employee", b =>
                {
                    b.HasOne("Entities.Models.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Entities.Models.Company", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
